import 'package:intl/intl.dart';

/// HTML mirror of PaymentProgressionPdfGenerator, rendered via Android's
/// native WebView print pipeline (see custom_report_pdf_generator.dart).
class PaymentProgressionHtmlGenerator {
  static final _currency = NumberFormat.currency(symbol: 'N', decimalDigits: 2);
  static final _dateFormat = DateFormat('dd MMM yyyy, hh:mm a');

  static String build({
    required List<Map<String, dynamic>> students,
    required String term,
    required String session,
    required String className,
    required String armName,
    required Map<String, dynamic> schoolProfile,
  }) {
    final classLabel = armName.isNotEmpty ? '$className ($armName)' : className;
    final generatedAt = _dateFormat.format(DateTime.now());

    double totalBill = 0, totalPaid = 0;
    int fullyPaid = 0;
    for (final s in students) {
      totalBill += (s['billTotal'] as num).toDouble();
      totalPaid += (s['totalPaid'] as num).toDouble();
      if ((s['totalPaid'] as num).toDouble() >= (s['billTotal'] as num).toDouble()) fullyPaid++;
    }
    final outstanding = totalBill - totalPaid;
    final avgCoverage = totalBill > 0 ? (totalPaid / totalBill * 100) : 0.0;

    final schoolName = (schoolProfile['schoolName']?.toString() ?? 'School');
    final address = (schoolProfile['address']?.toString() ?? '');
    final phone = (schoolProfile['phone']?.toString() ?? '');

    final studentSections = StringBuffer();
    for (final student in students) {
      studentSections.writeln(_buildStudentSection(student));
    }

    return '''
<!DOCTYPE html><html><head><meta charset="utf-8">
<style>
  @page { margin: 20px; }
  body { font-family: Helvetica, Arial, sans-serif; color: #1a1a1a; font-size: 11px; margin:0; padding:20px; }
  .center { text-align: center; }
  .right { text-align: right; }
  h1 { font-size: 15px; margin: 0; text-align:center; }
  .muted { color: #616161; text-align:center; font-size: 9px; }
  hr { border: none; border-top: 1.5px solid #ccc; margin: 6px 0; }
  .title { font-size: 13px; font-weight:bold; text-align:center; margin: 4px 0; }
  .info-row { display:flex; justify-content:space-between; font-size: 9px; margin-bottom: 4px; }
  .summary-box { border:1px solid #BDBDBD; background:#F5F5F5; border-radius:4px; padding:8px; display:flex; justify-content:space-around; margin-bottom: 14px; }
  .summary-item { text-align:center; }
  .summary-item .value { font-size:10px; font-weight:bold; }
  .summary-item .label { font-size:8px; color:#616161; }
  .student-card { border:1px solid #E0E0E0; border-radius:4px; padding:8px; margin-bottom:10px; page-break-inside: avoid; }
  .student-header { display:flex; justify-content:space-between; align-items:center; margin-bottom:6px; }
  .student-name { font-size:10px; font-weight:bold; }
  .student-meta { font-size:9px; color:#616161; }
  .coverage-badge { padding:3px 8px; border-radius:4px; color:white; font-size:9px; font-weight:bold; }
  table { width:100%; border-collapse: collapse; font-size: 8px; margin-bottom: 6px; }
  th, td { border:0.5px solid #E0E0E0; padding:3px 4px; }
  th { background:#EEEEEE; font-weight:bold; text-align:left; }
  .summary-row { display:flex; justify-content:flex-end; gap:12px; font-size:8px; }
  .summary-row .label { color:#616161; }
  .summary-row .value { font-weight:bold; }
  .footer-note { text-align:right; font-size:8px; color:#616161; margin-top: 10px; }
</style>
</head><body>
  <h1>${_esc(schoolName.toUpperCase())}</h1>
  ${address.isNotEmpty ? '<div class="muted">${_esc(address)}</div>' : ''}
  ${phone.isNotEmpty ? '<div class="muted">Tel: ${_esc(phone)}</div>' : ''}
  <hr>
  <div class="title">PAYMENT PROGRESSION REPORT</div>
  <div class="info-row">
    <span>Class: ${_esc(classLabel)}</span><span>${_esc(term)} | ${_esc(session)}</span><span>Generated: ${_esc(generatedAt)}</span>
  </div>
  <hr>

  <div class="summary-box">
    <div class="summary-item"><div class="value">${students.length}</div><div class="label">Students</div></div>
    <div class="summary-item"><div class="value">$fullyPaid</div><div class="label">Fully Paid</div></div>
    <div class="summary-item"><div class="value">${avgCoverage.toStringAsFixed(1)}%</div><div class="label">Avg Coverage</div></div>
    <div class="summary-item"><div class="value">${_currency.format(totalBill)}</div><div class="label">Total Billed</div></div>
    <div class="summary-item"><div class="value">${_currency.format(totalPaid)}</div><div class="label">Total Collected</div></div>
    <div class="summary-item"><div class="value">${_currency.format(outstanding < 0 ? 0 : outstanding)}</div><div class="label">Outstanding</div></div>
  </div>

  $studentSections

  <div class="footer-note">Generated by Bursary Manager</div>
</body></html>
''';
  }

  static String _buildStudentSection(Map<String, dynamic> student) {
    final surname = student['surname']?.toString() ?? '';
    final firstName = student['firstName']?.toString() ?? '';
    final admissionNo = student['admissionNo']?.toString() ?? '';
    final className = student['className']?.toString() ?? '';
    final armName = student['armName']?.toString() ?? '';
    final billTotal = (student['billTotal'] as num).toDouble();
    final totalPaid = (student['totalPaid'] as num?)?.toDouble() ?? 0.0;
    final outstanding = (billTotal - totalPaid).clamp(0.0, double.infinity);
    final progression = student['progression'] as List<Map<String, dynamic>>? ?? [];

    final coverage = billTotal > 0 ? totalPaid / billTotal : 0.0;
    final coverageColor = coverage >= 1.0 ? '#388E3C' : (coverage >= 0.4 ? '#F57C00' : '#D32F2F');
    final classLabel = armName.isNotEmpty ? '$className ($armName)' : className;

    final rows = StringBuffer();
    for (var i = 0; i < progression.length; i++) {
      final item = progression[i];
      final feeName = item['feeName']?.toString() ?? '';
      final amount = (item['amount'] as num).toDouble();
      final covered = (item['covered'] as num).toDouble();
      final status = item['status']?.toString() ?? '';
      final statusColor = status == 'Paid' ? '#388E3C' : (status == 'Partly Paid' ? '#F57C00' : '#757575');

      rows.writeln('<tr>'
          '<td>${i + 1}</td>'
          '<td>${_esc(feeName)}</td>'
          '<td class="right">${_currency.format(amount)}</td>'
          '<td class="center" style="color:$statusColor;">${_esc(status)}</td>'
          '<td class="right">${_currency.format(covered)}</td>'
          '</tr>');
    }

    final table = progression.isEmpty
        ? ''
        : '<table><thead><tr><th>#</th><th>Fee Item</th><th class="right">Amount</th><th class="center">Status</th><th class="right">Covered</th></tr></thead><tbody>$rows</tbody></table>';

    return '''
<div class="student-card">
  <div class="student-header">
    <div>
      <div class="student-name">${_esc('$surname, $firstName')}</div>
      <div class="student-meta">Adm: ${_esc(admissionNo)} | ${_esc(classLabel)}</div>
    </div>
    <span class="coverage-badge" style="background:$coverageColor;">${(coverage * 100).toStringAsFixed(1)}% paid</span>
  </div>
  $table
  <div class="summary-row">
    <span><span class="label">Bill Total: </span><span class="value">${_currency.format(billTotal)}</span></span>
    <span><span class="label">Total Paid: </span><span class="value">${_currency.format(totalPaid)}</span></span>
    <span><span class="label">Outstanding: </span><span class="value" style="color:${outstanding > 0 ? '#D32F2F' : '#388E3C'};">${_currency.format(outstanding)}</span></span>
  </div>
</div>
''';
  }

  static String _esc(dynamic value) {
    final s = value?.toString() ?? '';
    return s.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
  }
}
