import 'package:flutter/material.dart';

class AppGuideScreen extends StatelessWidget {
  const AppGuideScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey.shade50,
      body: CustomScrollView(
        slivers: [
          _buildHeader(context),
          SliverPadding(
            padding: const EdgeInsets.fromLTRB(16, 0, 16, 32),
            sliver: SliverList(
              delegate: SliverChildListDelegate([
                const SizedBox(height: 20),

                // ── Beginner Setup Guide ───────────────────────────────────
                _sectionLabel('Beginner Setup Guide'),
                const SizedBox(height: 8),
                _beginnerBanner(),
                const SizedBox(height: 10),
                _setupStepCard(
                  step: 1,
                  title: 'School Management',
                  color: Colors.deepPurple,
                  icon: Icons.account_balance_outlined,
                  subSteps: const [
                    _SubStep(
                      label: '(a) Set the Current Session / Term',
                      body:
                          'Go to School Management → Sessions & Terms.\n\n'
                          '• Tap "Add Session" and enter your academic year (e.g. 2024/2025).\n'
                          '• Under that session, tap "Add Term" and choose First Term, Second Term, or Third Term.\n'
                          '• Tap the 3-dot (⋮) menu beside the term and select "Set as Active".\n\n'
                          'This is the MOST IMPORTANT first step. Every bill, payment, and report is '
                          'tied to the active term. No billing is possible until a term is set as active.',
                    ),
                    _SubStep(
                      label: '(b) Enter the School Profile',
                      body:
                          'Go to School Management → School Profile.\n\n'
                          '• Enter the school name, address, phone number, and email.\n'
                          '• Optionally upload the school logo (appears on printed receipts and bills).\n'
                          '• Tap Save.\n\n'
                          'The school profile information is printed on every bill, receipt, report, '
                          'and debt notification letter generated by the app.',
                    ),
                    _SubStep(
                      label: '(c) Create Classes & Arms',
                      body:
                          'Go to School Management → Classes & Arms.\n\n'
                          '• Tap "Add Class" to create each class level (e.g. JSS 1, JSS 2, JSS 3, SS 1, SS 2, SS 3).\n'
                          '• After creating a class, tap it to open the Arms list.\n'
                          '• Tap "Add Arm" to create streams within that class (e.g. A, B, Gold, Silver).\n\n'
                          'Fee schedules are assigned per class/arm, so create all classes and arms '
                          'before setting up fee items.',
                    ),
                  ],
                ),
                const SizedBox(height: 10),
                _setupStepCard(
                  step: 2,
                  title: 'Student Management — Register Students',
                  color: Colors.green,
                  icon: Icons.people_outlined,
                  subSteps: const [
                    _SubStep(
                      label: 'Single Registration',
                      body:
                          'Go to Student Management → Students → tap the "+" button.\n\n'
                          '• Fill in the student\'s surname, first name, and other names.\n'
                          '• Select the student\'s class and arm.\n'
                          '• Enter the admission number (must be unique), date of birth, and gender.\n'
                          '• Optionally add a parent/guardian by linking an existing parent record or creating a new one.\n'
                          '• Tap Save.\n\n'
                          'Once saved, the student is immediately available for billing.',
                    ),
                    _SubStep(
                      label: 'Batch Registration (Multiple Students at Once)',
                      body:
                          'Go to Student Management → Students → tap the upload/import icon.\n\n'
                          '• Download the CSV template provided by the app.\n'
                          '• Fill in the student details in the template (one row per student).\n'
                          '• Import the completed CSV file back into the app.\n'
                          '• Review the preview and confirm the upload.\n\n'
                          'Batch upload is ideal at the start of a new term or when registering '
                          'many new students at once. It saves time compared to single entry.',
                    ),
                  ],
                ),
                const SizedBox(height: 10),
                _setupStepCard(
                  step: 3,
                  title: 'Bills & Payment — Fee Setup',
                  color: Colors.indigo,
                  icon: Icons.receipt_long_outlined,
                  subSteps: const [
                    _SubStep(
                      label: '(a)(i) Define Fee Items',
                      body:
                          'Go to Bills & Payment → Fee Items → tap "Add Fee Item".\n\n'
                          '• Enter a fee name (e.g. "School Fees", "Computer Levy", "Exam Fee").\n'
                          '• Set the default amount. Use 0 (zero) if the amount varies per class — '
                          'you will set the actual amount per class during assignment.\n'
                          '• Tap Save.\n\n'
                          'Define ALL the different types of fees your school charges. '
                          'Each item is a separate charge line that will appear on the student\'s bill.',
                    ),
                    _SubStep(
                      label: '(a)(ii) Assign Fees to Class / Arms',
                      body:
                          'Still in Bills & Payment → Fee Items → tap on a fee item → tap "Assign to Class".\n\n'
                          '• Select the target class (and arm, if applicable).\n'
                          '• Enter the exact amount for that class.\n'
                          '• Select the term and session this assignment applies to.\n'
                          '• Tap Assign.\n\n'
                          'Repeat for every class that pays this fee. Different classes can have '
                          'different amounts for the same fee item. A fee item must be assigned '
                          'to a class before a bill can be generated for students in that class.',
                    ),
                    _SubStep(
                      label: '(b)(i) New Intake — Special Bills Items',
                      body:
                          'Go to Bills & Payment → New Intake Bills → Special Bills Items.\n\n'
                          '• Define fee items that are ONLY charged to newly admitted students '
                          '(e.g. "Admission Fee", "Prospectus", "Development Levy").\n'
                          '• These items are separate from the regular term fees and appear '
                          'only on the bills of new students.\n'
                          '• Use 0 as the default amount if the fee varies per class.',
                    ),
                    _SubStep(
                      label: '(b)(ii) Assign Special Fees to Class / Arms',
                      body:
                          'Go to Bills & Payment → New Intake Bills → View New Intake Bills.\n\n'
                          '• Assign the special fee items to the appropriate classes and arms.\n'
                          '• Set the amount per class just as you did for regular fee items.\n\n'
                          'Once assigned, new intake fees will automatically be included in the '
                          'bill of any student registered as a new intake for that class.',
                    ),
                  ],
                ),

                const SizedBox(height: 24),

                // ── Quick Workflows ────────────────────────────────────────
                _sectionLabel('Quick Workflows'),
                const SizedBox(height: 10),
                _workflowCard(
                  title: 'Bill a Student',
                  color: Colors.indigo,
                  icon: Icons.receipt_long,
                  steps: const [
                    'Go to Bills & Payment → Student Bills',
                    'Search and select the student',
                    'Confirm the active term and session shown',
                    'Review the fee items and amounts assigned to the student\'s class',
                    'Tap Generate Bill',
                    'Print or share the bill receipt',
                  ],
                ),
                const SizedBox(height: 10),
                _workflowCard(
                  title: 'Record a Payment',
                  color: Colors.green,
                  icon: Icons.payments,
                  steps: const [
                    'Go to Bills & Payment → Payments',
                    'Search and select the student',
                    'Enter the amount paid',
                    'Select the payment method (Cash / POS / Bank Transfer / Others)',
                    'Add an optional note (e.g. bank teller number or reference)',
                    'Tap Record Payment',
                    'Print or share the payment receipt',
                  ],
                ),
                const SizedBox(height: 10),
                _workflowCard(
                  title: 'Set Up a New Term',
                  color: Colors.deepPurple,
                  icon: Icons.calendar_today,
                  steps: const [
                    'Go to School Management → Sessions & Terms',
                    'Create a new session if starting a new academic year',
                    'Add the term (First, Second, or Third) under the session',
                    'Tap the term menu (⋮) and set it as Active',
                    'Go to Bills & Payment → Fee Items',
                    'Assign fee items and amounts to each class for the new term',
                  ],
                ),
                const SizedBox(height: 10),
                _workflowCard(
                  title: 'Register a New Student',
                  color: Colors.teal,
                  icon: Icons.person_add,
                  steps: const [
                    'Go to Student Management → Students',
                    'Tap the "+" button to open the registration form',
                    'Fill in the student\'s full name, admission number, gender, and date of birth',
                    'Select the student\'s class and arm',
                    'Optionally link or create a parent/guardian record',
                    'Tap Save — the student is now ready for billing',
                  ],
                ),
                const SizedBox(height: 10),
                _workflowCard(
                  title: 'Send Debt Notification Letters',
                  color: Colors.red,
                  icon: Icons.mark_email_unread_outlined,
                  steps: const [
                    'Go to Bills & Payment → Debt Notification',
                    'On the Setup tab, choose the letter type (e.g. Current Term Debtors)',
                    'Select letters per page (1, 2, or 3) and set the letter date',
                    'Optionally set a payment deadline, signatory name, and custom text',
                    'Tap "Apply & View Students" to load the debtor list',
                    'Tap a student to preview or export their individual letter',
                    'Or tap "Export All PDF" to generate letters for all listed students at once',
                  ],
                ),
                const SizedBox(height: 10),
                _workflowCard(
                  title: 'Promote Students to Next Class',
                  color: Colors.deepPurple,
                  icon: Icons.arrow_upward_outlined,
                  steps: const [
                    'Go to Student Management → Promote Students',
                    'Select the source class (current class) and arm',
                    'Select the destination class (next class) and arm',
                    'Review the list of students to be promoted',
                    'Tap Promote — the selected students move to the new class',
                    'Students who should not be promoted can be unchecked before confirming',
                  ],
                ),

                const SizedBox(height: 24),

                // ── Module Guide ───────────────────────────────────────────
                _sectionLabel('Module Guide'),
                const SizedBox(height: 10),
                ..._modules(),

                const SizedBox(height: 24),

                // ── Operational Manual ─────────────────────────────────────
                _sectionLabel('Operational Manual'),
                const SizedBox(height: 10),
                _operationCard(
                  title: 'Daily Operations',
                  icon: Icons.wb_sunny_outlined,
                  color: Colors.orange,
                  procedures: const [
                    _Procedure(
                      'Morning Setup',
                      'Verify the correct term is active — the active term is shown in the sidebar at all times. '
                      'Check the Dashboard for an overview of today\'s outstanding balances. '
                      'If using multi-device mode, verify the last sync timestamp on the Dashboard.',
                    ),
                    _Procedure(
                      'Recording Payments',
                      'Go to Bills & Payment → Payments. Search by student name or admission number. '
                      'Enter the exact amount paid, select the payment method (Cash / POS / Transfer), '
                      'and add an optional reference (e.g. bank teller number). '
                      'Tap Record Payment and print or share the receipt immediately.',
                    ),
                    _Procedure(
                      'Generating Bills',
                      'Go to Bills & Payment → Student Bills. Select the student, '
                      'confirm the fee items are correct, and tap Generate Bill. '
                      'Any unpaid balance from a previous term is automatically carried forward as "Previous Balance".',
                    ),
                    _Procedure(
                      'End-of-Day Reconciliation',
                      'Go to Reports → Daily Report and select today\'s date. '
                      'The report lists every payment collected, the method, and the total. '
                      'Cross-check against cash in hand and POS/transfer receipts. Print the report for filing.',
                    ),
                    _Procedure(
                      'Daily Backup',
                      'Go to Preferences → Backup and tap "Backup Now". '
                      'If cloud sync is enabled, verify the last sync timestamp is current. '
                      'A daily backup protects your data against device loss or failure.',
                    ),
                  ],
                ),
                const SizedBox(height: 10),
                _operationCard(
                  title: 'Term Operations',
                  icon: Icons.event_note_outlined,
                  color: Colors.blue,
                  procedures: const [
                    _Procedure(
                      'Before Term Begins — Activate the New Term',
                      'Go to School Management → Sessions & Terms. '
                      'Tap the 3-dot menu beside the new term and select "Set as Active". '
                      'The active term label in the sidebar will update immediately.',
                    ),
                    _Procedure(
                      'Before Term Begins — Assign Fees',
                      'Go to Bills & Payment → Fee Items. For each class, assign the applicable '
                      'fee items and amounts for the new term. Double-check against the school\'s '
                      'approved fee schedule before billing begins.',
                    ),
                    _Procedure(
                      'Before Term Begins — New Intake Students',
                      'Register new students under Student Management → Students. '
                      'For one-time admission fees, define them under Bills & Payment → New Intake Bills → Special Bills Items, '
                      'then assign them to the appropriate classes.',
                    ),
                    _Procedure(
                      'During Term — Monitor Debtors',
                      'Regularly check Bills & Payment → Debtors for students with unpaid balances in the current term. '
                      'Use Bills & Payment → Last Term Debtors to track students who have not yet cleared fees from the previous term. '
                      'Use Bills & Payment → Debt Notification to generate and print/share formal reminder letters.',
                    ),
                    _Procedure(
                      'During Term — Track Overpayments',
                      'Go to Bills & Payment → Overpayment Tracker to identify students who have '
                      'paid more than their total bill. Arrange refunds or carry the credit forward to the next term.',
                    ),
                    _Procedure(
                      'End of Term — Generate Termly Report',
                      'Go to Reports → Termly Report. Select the term and session. '
                      'The report shows total billed, total collected, and outstanding per class. '
                      'Print or export for management review and filing.',
                    ),
                    _Procedure(
                      'End of Term — Backup Before Closing',
                      'Always create a full backup BEFORE switching to a new term. '
                      'Go to Preferences → Backup, export to a file, and store a copy in Google Drive. '
                      'Label the backup with the term and session name for easy retrieval.',
                    ),
                    _Procedure(
                      'Activating the Next Term',
                      'Go to School Management → Sessions & Terms. '
                      'Create the next term (or a new session if starting a new academic year). '
                      'Set it as active. Previous unpaid balances automatically appear as '
                      '"Previous Balance" on new bills generated in the new term.',
                    ),
                  ],
                ),
                const SizedBox(height: 10),
                _operationCard(
                  title: 'Annual Operations',
                  icon: Icons.event_repeat_outlined,
                  color: Colors.deepPurple,
                  procedures: const [
                    _Procedure(
                      'Start a New Academic Session',
                      'Go to School Management → Sessions & Terms. '
                      'Create a new session (e.g. 2025/2026). Add its First Term and set it as active. '
                      'Reassign fee items for each class under Bills & Payment → Fee Items.',
                    ),
                    _Procedure(
                      'Promote Students to the Next Class',
                      'Go to Student Management → Promote Students. '
                      'Select the source class and destination class for each set of students. '
                      'Students who should repeat or leave can be excluded before confirming promotion.',
                    ),
                    _Procedure(
                      'Deactivate / Graduate Students',
                      'Go to Student Management → Deactivate Student. '
                      'Select students who have completed their final year or have left the school. '
                      'Deactivated students remain in the database for record purposes but are '
                      'excluded from active billing. They can be viewed under Inactive Students.',
                    ),
                    _Procedure(
                      'Annual Backup & Archive',
                      'After the Third Term of the session, export a full backup to Google Drive '
                      'and also save a local copy. Label the backup file with the session name (e.g. "Backup_2024_2025") '
                      'so it can be easily retrieved years later.',
                    ),
                    _Procedure(
                      'Renew License',
                      'Go to Preferences → License to check your subscription expiry date. '
                      'Renew before it expires to avoid any interruption to the app\'s functionality.',
                    ),
                    _Procedure(
                      'Review User Accounts',
                      'Go to Preferences → User Management (Super Admin only). '
                      'Remove accounts for staff who have left the school '
                      'and update module permissions for existing users as their roles change.',
                    ),
                  ],
                ),
                const SizedBox(height: 10),
                _operationCard(
                  title: 'Troubleshooting',
                  icon: Icons.build_outlined,
                  color: Colors.red,
                  procedures: const [
                    _Procedure(
                      'Bill not generating for a student',
                      'Fee items must be assigned to the student\'s class for the active term. '
                      'Go to Bills & Payment → Fee Items, select a fee item, and verify it is '
                      'assigned to the student\'s class with the correct term and session.',
                    ),
                    _Procedure(
                      'Previous balance amount seems wrong',
                      'The previous balance is calculated from all bills minus all payments before the current term. '
                      'Open the student\'s profile and tap the history/statement icon to review '
                      'their full billing and payment history across all terms.',
                    ),
                    _Procedure(
                      'Student does not appear in search',
                      'The student may have been deactivated (graduated, withdrawn, or transferred). '
                      'Go to Student Management → Inactive Students to find and reactivate them if needed.',
                    ),
                    _Procedure(
                      'No students appear on the Debtors list',
                      'Ensure fee items have been assigned to the active term. '
                      'A student only appears as a debtor if a bill has been generated for them '
                      'in the current active term and the bill remains unpaid or partially paid.',
                    ),
                    _Procedure(
                      'Cloud sync not working',
                      'Go to Preferences → Backup. Check that the device is connected to the internet '
                      'and that the Google account is authenticated. '
                      'Try signing out of the Google account and re-authenticating.',
                    ),
                    _Procedure(
                      'Receipt not printing',
                      'Ensure a Bluetooth or USB printer is connected and paired. '
                      'Check printer settings under Preferences → Thermal Printer. '
                      'Use the "Share" option to export the receipt as a PDF and send via WhatsApp or email instead.',
                    ),
                    _Procedure(
                      'Data appears incorrect after restoring a backup',
                      'After restoring, fully close and restart the app. '
                      'If the issue persists, the backup file may be from a different version of the database. '
                      'Try restoring from a different backup point.',
                    ),
                    _Procedure(
                      'User cannot access a module',
                      'Go to Preferences → User Management (Super Admin only). '
                      'Select the user and enable the relevant module permission. '
                      'The user must log out and log back in for the change to take effect.',
                    ),
                    _Procedure(
                      'Fee items show wrong amounts after a new term',
                      'Fee item assignments are per term. When a new term is activated, you must '
                      're-assign fee items to each class for the new term. '
                      'Go to Bills & Payment → Fee Items and repeat the class assignment for the new term.',
                    ),
                  ],
                ),
                const SizedBox(height: 10),
                _operationCard(
                  title: 'User Roles & Permissions',
                  icon: Icons.manage_accounts_outlined,
                  color: Colors.blueGrey,
                  procedures: const [
                    _Procedure(
                      'Super Admin',
                      'Full access to all modules including User Management, License, Clear Data, '
                      'Server Management, and all financial records. '
                      'Should be reserved for the system administrator or school proprietor. '
                      'The Super Admin account cannot be deleted.',
                    ),
                    _Procedure(
                      'Admin',
                      'Access to most modules. Cannot manage licenses or clear data by default. '
                      'Permissions can be individually toggled per module in User Management.',
                    ),
                    _Procedure(
                      'Bursar',
                      'Typically granted access to billing, payments, reports, and debt notification. '
                      'Cannot access user management, license, or server settings unless explicitly granted.',
                    ),
                    _Procedure(
                      'Customising Permissions',
                      'Go to Preferences → Permissions (Super Admin only). '
                      'Select a user type and toggle access for each module independently. '
                      'Changes apply to all users of that type on their next login.',
                    ),
                    _Procedure(
                      'Multi-Device Mode (Server / Client)',
                      'One device acts as the Server (holds the master database). '
                      'Other devices connect as Clients and access data in real time over Wi-Fi. '
                      'Configure this under Preferences → Server Management on the server device, '
                      'and Client Connection on the client devices.',
                    ),
                  ],
                ),

                const SizedBox(height: 24),

                // ── Tips & Notes ───────────────────────────────────────────
                _sectionLabel('Tips & Notes'),
                const SizedBox(height: 10),
                _tipsCard(),
              ]),
            ),
          ),
        ],
      ),
    );
  }

  // ── Header ───────────────────────────────────────────────────────────────

  Widget _buildHeader(BuildContext context) {
    return SliverAppBar(
      expandedHeight: 200,
      pinned: true,
      backgroundColor: Colors.teal.shade800,
      iconTheme: const IconThemeData(color: Colors.white),
      flexibleSpace: FlexibleSpaceBar(
        background: Container(
          decoration: BoxDecoration(
            gradient: LinearGradient(
              colors: [Colors.teal.shade900, Colors.teal.shade500],
              begin: Alignment.topLeft,
              end: Alignment.bottomRight,
            ),
          ),
          child: SafeArea(
            child: Padding(
              padding: const EdgeInsets.fromLTRB(20, 48, 20, 20),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                mainAxisAlignment: MainAxisAlignment.end,
                children: [
                  Row(
                    children: [
                      Container(
                        padding: const EdgeInsets.all(10),
                        decoration: BoxDecoration(
                          color: Colors.white.withValues(alpha: 0.15),
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: const Icon(Icons.menu_book,
                            color: Colors.white, size: 28),
                      ),
                      const SizedBox(width: 14),
                      const Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'App Guide',
                              style: TextStyle(
                                color: Colors.white,
                                fontSize: 24,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                            SizedBox(height: 4),
                            Text(
                              'School Bursary Manager — Full Documentation',
                              style:
                                  TextStyle(color: Colors.white70, fontSize: 13),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ),
        ),
        title: const Text(
          'App Guide',
          style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
        ),
        titlePadding: const EdgeInsets.only(left: 56, bottom: 16),
      ),
    );
  }

  // ── Beginner banner ───────────────────────────────────────────────────────

  Widget _beginnerBanner() {
    return Container(
      decoration: BoxDecoration(
        gradient: LinearGradient(
          colors: [Colors.teal.shade700, Colors.teal.shade500],
        ),
        borderRadius: BorderRadius.circular(14),
      ),
      padding: const EdgeInsets.all(14),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: Colors.white.withValues(alpha: 0.2),
              shape: BoxShape.circle,
            ),
            child: const Icon(Icons.rocket_launch_outlined,
                color: Colors.white, size: 22),
          ),
          const SizedBox(width: 12),
          const Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Start Here — First-Time Setup',
                  style: TextStyle(
                    color: Colors.white,
                    fontWeight: FontWeight.bold,
                    fontSize: 14,
                  ),
                ),
                SizedBox(height: 3),
                Text(
                  'Follow these 3 steps in order before billing any student. '
                  'Tap each step below to expand the instructions.',
                  style: TextStyle(color: Colors.white70, fontSize: 12, height: 1.4),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  // ── Setup step card ────────────────────────────────────────────────────────

  Widget _setupStepCard({
    required int step,
    required String title,
    required Color color,
    required IconData icon,
    required List<_SubStep> subSteps,
  }) {
    return Card(
      elevation: 1,
      shadowColor: Colors.black12,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(14),
        side: BorderSide(color: color.withValues(alpha: 0.25)),
      ),
      child: Theme(
        data: ThemeData().copyWith(dividerColor: Colors.transparent),
        child: ExpansionTile(
          leading: Container(
            width: 36,
            height: 36,
            alignment: Alignment.center,
            decoration: BoxDecoration(
              color: color,
              shape: BoxShape.circle,
            ),
            child: Text(
              '$step',
              style: const TextStyle(
                color: Colors.white,
                fontWeight: FontWeight.bold,
                fontSize: 16,
              ),
            ),
          ),
          title: Text(title,
              style:
                  const TextStyle(fontWeight: FontWeight.w700, fontSize: 14)),
          childrenPadding: const EdgeInsets.fromLTRB(14, 0, 14, 14),
          children: subSteps.map((s) {
            return Padding(
              padding: const EdgeInsets.only(top: 12),
              child: Container(
                decoration: BoxDecoration(
                  color: color.withValues(alpha: 0.05),
                  borderRadius: BorderRadius.circular(10),
                  border: Border.all(color: color.withValues(alpha: 0.15)),
                ),
                padding: const EdgeInsets.all(12),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Icon(Icons.subdirectory_arrow_right,
                            size: 14, color: color),
                        const SizedBox(width: 6),
                        Expanded(
                          child: Text(
                            s.label,
                            style: TextStyle(
                              fontSize: 13,
                              fontWeight: FontWeight.bold,
                              color: color.withValues(alpha: 0.85),
                            ),
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 8),
                    Text(
                      s.body,
                      style: TextStyle(
                          fontSize: 12.5,
                          color: Colors.grey.shade700,
                          height: 1.5),
                    ),
                  ],
                ),
              ),
            );
          }).toList(),
        ),
      ),
    );
  }

  // ── Helpers ──────────────────────────────────────────────────────────────

  Widget _sectionLabel(String text) {
    return Padding(
      padding: const EdgeInsets.only(left: 2),
      child: Row(
        children: [
          Container(
            width: 4,
            height: 20,
            decoration: BoxDecoration(
              color: Colors.teal.shade700,
              borderRadius: BorderRadius.circular(2),
            ),
          ),
          const SizedBox(width: 10),
          Text(
            text,
            style: TextStyle(
              fontSize: 16,
              fontWeight: FontWeight.bold,
              color: Colors.grey.shade800,
            ),
          ),
        ],
      ),
    );
  }

  Widget _workflowCard({
    required String title,
    required Color color,
    required IconData icon,
    required List<String> steps,
  }) {
    return Card(
      elevation: 1,
      shadowColor: Colors.black12,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
      child: Theme(
        data: ThemeData().copyWith(dividerColor: Colors.transparent),
        child: ExpansionTile(
          leading: Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: color.withValues(alpha: 0.12),
              borderRadius: BorderRadius.circular(8),
            ),
            child: Icon(icon, color: color, size: 20),
          ),
          title: Text(title,
              style:
                  const TextStyle(fontWeight: FontWeight.w600, fontSize: 14)),
          childrenPadding: const EdgeInsets.fromLTRB(16, 0, 16, 14),
          children: steps.asMap().entries.map((e) {
            final i = e.key + 1;
            return Padding(
              padding: const EdgeInsets.only(top: 8),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Container(
                    width: 22,
                    height: 22,
                    alignment: Alignment.center,
                    decoration: BoxDecoration(
                      color: color.withValues(alpha: 0.15),
                      shape: BoxShape.circle,
                    ),
                    child: Text(
                      '$i',
                      style: TextStyle(
                        fontSize: 11,
                        fontWeight: FontWeight.bold,
                        color: color,
                      ),
                    ),
                  ),
                  const SizedBox(width: 10),
                  Expanded(
                    child: Text(e.value,
                        style:
                            const TextStyle(fontSize: 13, height: 1.4)),
                  ),
                ],
              ),
            );
          }).toList(),
        ),
      ),
    );
  }

  Widget _operationCard({
    required String title,
    required IconData icon,
    required Color color,
    required List<_Procedure> procedures,
  }) {
    return Card(
      elevation: 1,
      shadowColor: Colors.black12,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
      child: Theme(
        data: ThemeData().copyWith(dividerColor: Colors.transparent),
        child: ExpansionTile(
          leading: Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: color.withValues(alpha: 0.12),
              borderRadius: BorderRadius.circular(8),
            ),
            child: Icon(icon, color: color, size: 20),
          ),
          title: Text(title,
              style: const TextStyle(
                  fontWeight: FontWeight.w700, fontSize: 14)),
          childrenPadding: const EdgeInsets.fromLTRB(14, 0, 14, 14),
          children: procedures.asMap().entries.map((e) {
            final isLast = e.key == procedures.length - 1;
            final p = e.value;
            return Column(
              children: [
                Padding(
                  padding: const EdgeInsets.only(top: 10),
                  child: Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        width: 8,
                        height: 8,
                        margin: const EdgeInsets.only(top: 4),
                        decoration: BoxDecoration(
                          color: color.withValues(alpha: 0.6),
                          shape: BoxShape.circle,
                        ),
                      ),
                      const SizedBox(width: 10),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(p.title,
                                style: const TextStyle(
                                    fontWeight: FontWeight.w600,
                                    fontSize: 13)),
                            const SizedBox(height: 3),
                            Text(p.description,
                                style: TextStyle(
                                    fontSize: 12,
                                    color: Colors.grey.shade600,
                                    height: 1.4)),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
                if (!isLast)
                  Divider(
                    height: 14,
                    indent: 18,
                    color: Colors.grey.shade100,
                  ),
              ],
            );
          }).toList(),
        ),
      ),
    );
  }

  List<Widget> _modules() {
    final modules = [
      _ModuleData(
        title: 'Dashboard',
        subtitle: 'Live financial summary and statistics',
        icon: Icons.dashboard_outlined,
        color: Colors.blue,
        features: const [
          _Feature(Icons.bar_chart, 'Financial Overview',
              'Shows total bills, total collected, and outstanding fees for the active term at a glance. '
              'Financial figures are PIN-protected for privacy.'),
          _Feature(Icons.people, 'Student Summary',
              'Displays counts of total active students, inactive/deactivated students, and current debtors.'),
          _Feature(Icons.notifications_outlined, 'Backup Reminder',
              'Alerts you when you have not backed up in a while, with escalating urgency levels '
              '(gentle → medium → critical).'),
          _Feature(Icons.calendar_today, 'Active Term Display',
              'The current active term and session are always visible in the sidebar so you always '
              'know which period you are working in.'),
        ],
      ),
      _ModuleData(
        title: 'School Management',
        subtitle: 'Profile, classes, arms, sessions & terms',
        icon: Icons.account_balance_outlined,
        color: Colors.deepPurple,
        features: const [
          _Feature(Icons.business, 'School Profile',
              'Enter your school\'s name, address, phone, email, and logo. '
              'This information is printed on every receipt, bill, report, and notification letter.'),
          _Feature(Icons.class_outlined, 'Classes',
              'Create and manage class levels (e.g. JSS 1, JSS 2, SS 1, SS 2). '
              'Each class can have multiple arms/streams.'),
          _Feature(Icons.groups_outlined, 'Arms',
              'Add sub-groups within a class (e.g. A, B, Gold, Silver). '
              'Fee assignments can be made at the class level or differentiated per arm.'),
          _Feature(Icons.calendar_month, 'Sessions & Terms',
              'Create academic sessions (e.g. 2024/2025) and terms within each session. '
              'Set one term as active at any time — all billing and reporting use the active term. '
              'Previous term outstanding balances carry forward automatically.'),
        ],
      ),
      _ModuleData(
        title: 'Student Management',
        subtitle: 'Register, manage, promote & track students',
        icon: Icons.people_outlined,
        color: Colors.green,
        features: const [
          _Feature(Icons.person_add, 'Single Registration',
              'Register a student individually with full personal details, class/arm assignment, '
              'and optional parent link. Admission number must be unique.'),
          _Feature(Icons.upload_file, 'Batch Upload (CSV)',
              'Upload multiple students at once using a CSV template. '
              'Ideal for registering a whole class at the start of a term. '
              'The app validates each row before importing.'),
          _Feature(Icons.edit, 'Edit Student',
              'Update any student detail — name, class, arm, contact, or status. '
              'View the student\'s full billing and payment history from the detail page.'),
          _Feature(Icons.receipt, 'Student Statement',
              'View a full statement of all bills generated and all payments made by a student '
              'across all terms, with outstanding balance per term.'),
          _Feature(Icons.person_add_outlined, 'View New Students',
              'Filter and view only students who were registered in the current term — '
              'useful for confirming new intake entries.'),
          _Feature(Icons.arrow_upward_outlined, 'Promote Students',
              'Move an entire class or selected students to the next class level at the end of a session. '
              'Exclude students who are repeating or have left.'),
          _Feature(Icons.person_remove_outlined, 'Deactivate Student',
              'Mark a student as inactive (graduated, withdrawn, or transferred). '
              'Deactivated students are excluded from billing but their records are preserved.'),
          _Feature(Icons.archive_outlined, 'Inactive Students',
              'View all deactivated students. Reactivate a student if they return to the school.'),
          _Feature(Icons.family_restroom_outlined, 'Siblings',
              'Link students who are siblings (share the same parent/guardian). '
              'Useful for applying family discounts or managing related accounts.'),
          _Feature(Icons.warning_amber, 'Debtors List',
              'Quick view of all students with outstanding balances in the active term. '
              'Filter by class or arm, and export the list.'),
          _Feature(Icons.receipt_long_outlined, 'Class Bills',
              'View all bills and payment statuses for every student in a selected class at once.'),
        ],
      ),
      _ModuleData(
        title: 'Parents Management',
        subtitle: 'Parent and guardian records',
        icon: Icons.family_restroom_outlined,
        color: Colors.teal,
        features: const [
          _Feature(Icons.person, 'Register Parent',
              'Add a parent or guardian record with their name, phone number, and address. '
              'A parent can be linked to multiple students (siblings).'),
          _Feature(Icons.link, 'Link to Student',
              'Associate a parent record with one or more students. '
              'Linked parents can be viewed from the student\'s detail page.'),
          _Feature(Icons.contact_phone, 'All Parents Directory',
              'Browse and search the complete list of all registered parents and guardians. '
              'Contact details are displayed for quick reference.'),
        ],
      ),
      _ModuleData(
        title: 'Bills & Payment',
        subtitle: 'Fee setup, billing, payments & notification letters',
        icon: Icons.receipt_long_outlined,
        color: Colors.indigo,
        features: const [
          _Feature(Icons.list_alt_outlined, 'Fee Items',
              'Define individual fee components (e.g. Tuition, PTA Levy, Development Fee, Books). '
              'Each item has a default amount that can be overridden per class. '
              'Fee items must be assigned to a class/term before billing can begin.'),
          _Feature(Icons.receipt_outlined, 'Student Bills',
              'Generate a bill for a specific student. The bill auto-includes all fee items '
              'assigned to the student\'s class for the active term, plus any previous unpaid balance.'),
          _Feature(Icons.payment_outlined, 'Payments',
              'Record payments against a student\'s bill. Supports Cash, POS, Bank Transfer, '
              'and other payment methods. Each payment generates a printable/shareable receipt. '
              'Partial payments are supported.'),
          _Feature(Icons.account_balance_wallet, 'Overpayment Tracker',
              'Identifies students who have paid more than their total bill. '
              'Helps manage refunds or credit carry-forwards to the next term.'),
          _Feature(Icons.warning_amber, 'Debtors (Current Term)',
              'Lists all students with an unpaid or partially paid balance in the active term. '
              'Filter by class or search by name. Export the list as needed.'),
          _Feature(Icons.history_edu_outlined, 'Last Term Debtors',
              'Shows students who still have an uncleared balance from the previous term. '
              'Helps track students who carry recurring debt across terms.'),
          _Feature(Icons.mark_email_unread_outlined, 'Debt Notification Letters',
              'Generate formal debt reminder letters in PDF format. '
              'Five letter types: Current Term Debtors, Last Term Debtors, Zero Payment (nothing paid), '
              'PTA Meeting Notification (all parents), and Mid-Term Holiday Notice. '
              'Choose 1, 2, or 3 letters per A4 page to save printing costs. '
              'Bulk-generate for all debtors or export individual letters per student.'),
          _Feature(Icons.person_add_alt_1, 'New Intake Bills — Special Items',
              'Define one-time fees specific to newly admitted students (e.g. Admission Fee, Prospectus). '
              'These fees are separate from regular term fees and apply only to new intakes.'),
          _Feature(Icons.visibility_outlined, 'New Intake Bills — View Bills',
              'Review and manage the bills generated for new intake students, '
              'with the special fee items included alongside regular term fees.'),
          _Feature(Icons.low_priority_outlined, 'Fee Tracker — Set Bill Priority',
              'Define the order in which fee items are settled when a student makes a partial payment. '
              'For example, set Tuition to be settled before PTA Levy.'),
          _Feature(Icons.manage_search_outlined, 'Fee Tracker — Track Fee Item',
              'See how payments for a specific fee item are distributed across all students '
              'in a class. Useful for monitoring collection of a particular levy.'),
          _Feature(Icons.bar_chart_outlined, 'Fee Tracker — Payment Progression',
              'Visualise the payment progression for a class over a term — '
              'how much has been collected versus how much is outstanding, broken down by fee item.'),
        ],
      ),
      _ModuleData(
        title: 'Reports',
        subtitle: 'Daily, termly, sales & print analytics',
        icon: Icons.bar_chart_outlined,
        color: Colors.deepOrange,
        features: const [
          _Feature(Icons.today, 'Daily Report',
              'A detailed summary of all payments collected on a selected date. '
              'Grouped by payment method (Cash, POS, Transfer). Printable for daily filing.'),
          _Feature(Icons.calendar_month, 'Termly Report',
              'A full financial summary for a selected term: total billed, total collected, '
              'and outstanding per class and overall. Ideal for management review and school accounts.'),
          _Feature(Icons.point_of_sale_outlined, 'Sales Report',
              'Daily breakdown of stock/tuck shop sales revenue, grouped by item and buyer type.'),
          _Feature(Icons.print_outlined, 'Daily Print Count',
              'Track the number of receipts, bills, and reports printed per day. '
              'Helps monitor usage and printing costs.'),
        ],
      ),
      _ModuleData(
        title: 'Stock & Sales',
        subtitle: 'School store inventory and sales records',
        icon: Icons.inventory_2_outlined,
        color: Colors.brown,
        features: const [
          _Feature(Icons.inventory_outlined, 'Stock Items',
              'Add items to the school store with name, quantity, buying price, and selling price. '
              'The app tracks stock levels as sales are recorded.'),
          _Feature(Icons.local_shipping_outlined, 'Suppliers',
              'Maintain a list of suppliers/vendors for stock items. '
              'Each stock item can be linked to a supplier for procurement records.'),
          _Feature(Icons.history_outlined, 'Purchase History',
              'View all stock purchase/restock records with dates, quantities, and costs.'),
          _Feature(Icons.point_of_sale_outlined, 'Sales',
              'Record a sale by selecting the buyer (a student or walk-in customer), '
              'choosing items and quantities, and confirming the transaction. '
              'A receipt can be printed or shared.'),
          _Feature(Icons.assessment_outlined, 'Stock Report',
              'View total stock value, items sold, revenue, and low-stock items. '
              'Helps manage inventory levels and profitability.'),
        ],
      ),
      _ModuleData(
        title: 'Expenditure',
        subtitle: 'Track and categorise school expenses',
        icon: Icons.money_off_outlined,
        color: Colors.purple,
        features: const [
          _Feature(Icons.add_circle_outline, 'Record Expense',
              'Log a school expense with date, category, description, and amount. '
              'Useful for tracking petty cash, maintenance costs, and operational spending.'),
          _Feature(Icons.list_outlined, 'Expense List',
              'Browse all recorded expenses, filterable by date range or category. '
              'Shows the total expenditure for the selected period.'),
          _Feature(Icons.label_outline, 'Expense Categories',
              'Create and manage expense categories (e.g. Utilities, Maintenance, Stationery) '
              'to organise spending records for budget analysis.'),
        ],
      ),
      _ModuleData(
        title: 'Staff Management',
        subtitle: 'Staff records, payroll, loans & deductions',
        icon: Icons.badge_outlined,
        color: Colors.indigo,
        features: const [
          _Feature(Icons.person_add, 'Register Staff',
              'Add a staff member with personal details, office/department, class allocation, '
              'and a photo. Each staff record has a unique staff ID.'),
          _Feature(Icons.business, 'Staff Offices',
              'Define the offices/departments in the school (e.g. Admin, Academic, Accounts). '
              'Each staff member is assigned to an office.'),
          _Feature(Icons.class_outlined, 'Class Allocation',
              'Assign staff members to specific classes they are responsible for '
              '(e.g. class teacher assignments).'),
          _Feature(Icons.meeting_room_outlined, 'Office Allocation',
              'Assign staff to specific offices, mapping their role to a department.'),
          _Feature(Icons.attach_money, 'Salary Setup',
              'Define monthly salary amounts for each staff member. '
              'The salary serves as the base for payroll calculations.'),
          _Feature(Icons.people, 'Staff List',
              'Browse all active staff records with their details, photo, office, and salary information.'),
          _Feature(Icons.card_giftcard_outlined, 'Incentives / Grants',
              'Record bonuses, allowances, or one-time grants paid to a staff member '
              'with the date and reason.'),
          _Feature(Icons.account_balance_wallet_outlined, 'Staff Loans',
              'Record salary loans advanced to staff members and track their repayment progress.'),
          _Feature(Icons.remove_circle_outline, 'Penalties / Deductions',
              'Record penalty deductions against a staff member\'s salary '
              'with the reason and amount.'),
          _Feature(Icons.payment_outlined, 'Staff Payroll',
              'Generate monthly payslips for staff. Payroll automatically accounts for '
              'base salary, incentives, loan repayments, and deductions. '
              'Print or export each payslip.'),
        ],
      ),
      _ModuleData(
        title: 'Preferences',
        subtitle: 'Backup, license, display, users & network',
        icon: Icons.settings_outlined,
        color: Colors.blueGrey,
        features: const [
          _Feature(Icons.backup, 'Backup & Restore',
              'Export the entire database to a local file or Google Drive. '
              'Restore from a previous backup at any time. '
              'The app shows the date and size of the last backup.'),
          _Feature(Icons.cloud_sync, 'Cloud Sync (Google Drive)',
              'Automatically sync data to Google Drive for access across devices. '
              'One device acts as the master (host); others receive updates. '
              'Useful for multi-device setups in a school network.'),
          _Feature(Icons.vpn_key, 'License',
              'View your current subscription status, expiry date, and device ID. '
              'Activate a new license or renew an existing one.'),
          _Feature(Icons.print_outlined, 'Thermal Printer',
              'Configure a Bluetooth or USB thermal printer for receipt printing. '
              'Test the connection and set default paper width.'),
          _Feature(Icons.display_settings, 'Display Settings',
              'Adjust font size, card density, and layout scale to suit your screen size and preference.'),
          _Feature(Icons.security_outlined, 'Security',
              'Change login credentials (username and password) for the current account. '
              'Enable or disable auto-lock settings.'),
          _Feature(Icons.manage_accounts, 'User Management',
              'Create additional user accounts (Admin or Bursar type) and control '
              'which modules each user can access. Super Admin only.'),
          _Feature(Icons.admin_panel_settings_outlined, 'Permissions',
              'Fine-grained control over which modules each user type (Admin / Bursar) can view or edit. '
              'Changes take effect on next login. Super Admin only.'),
          _Feature(Icons.dns_outlined, 'Server Management',
              'Configure this device as a data server for a local school network. '
              'Other devices on the same Wi-Fi connect as clients and access data in real time. '
              'Super Admin only.'),
          _Feature(Icons.storage_outlined, 'Data Management',
              'Selectively clear term data, reset student balances, or wipe specific records. '
              'Use with extreme caution — cleared data cannot be recovered without a backup.'),
        ],
      ),
      _ModuleData(
        title: 'Updates',
        subtitle: 'App news, release notes & downloads',
        icon: Icons.system_update_outlined,
        color: Colors.cyan,
        features: const [
          _Feature(Icons.web, 'In-App Updates Page',
              'Loads the TY Solutions updates page directly inside the app. '
              'Stay informed about new features, bug fixes, and announcements. '
              'Download links for new APK versions open in the external browser automatically.'),
        ],
      ),
    ];

    return modules
        .map((m) => Padding(
              padding: const EdgeInsets.only(bottom: 8),
              child: _moduleCard(m),
            ))
        .toList();
  }

  Widget _moduleCard(_ModuleData m) {
    return Card(
      elevation: 1,
      shadowColor: Colors.black12,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
      child: Theme(
        data: ThemeData().copyWith(dividerColor: Colors.transparent),
        child: ExpansionTile(
          leading: Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: m.color.withValues(alpha: 0.12),
              borderRadius: BorderRadius.circular(8),
            ),
            child: Icon(m.icon, color: m.color, size: 20),
          ),
          title: Text(m.title,
              style:
                  const TextStyle(fontWeight: FontWeight.w700, fontSize: 14)),
          subtitle: Text(m.subtitle,
              style: TextStyle(fontSize: 11, color: Colors.grey.shade600)),
          childrenPadding: const EdgeInsets.fromLTRB(12, 0, 12, 12),
          children: m.features
              .map((f) => ListTile(
                    dense: true,
                    contentPadding:
                        const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                    leading: Container(
                      width: 32,
                      height: 32,
                      alignment: Alignment.center,
                      decoration: BoxDecoration(
                        color: m.color.withValues(alpha: 0.08),
                        borderRadius: BorderRadius.circular(6),
                      ),
                      child: Icon(f.icon, size: 16, color: m.color),
                    ),
                    title: Text(f.title,
                        style: const TextStyle(
                            fontSize: 13, fontWeight: FontWeight.w600)),
                    subtitle: Text(f.description,
                        style: TextStyle(
                            fontSize: 12,
                            color: Colors.grey.shade600,
                            height: 1.4)),
                  ))
              .toList(),
        ),
      ),
    );
  }

  Widget _tipsCard() {
    final tips = [
      (
        'Set the active term first — always',
        'Before doing anything else in the app, go to School Management → Sessions & Terms '
        'and ensure the correct term is set as active. The active term controls all billing, '
        'payments, and reports. It is shown in the sidebar at all times.',
        Icons.calendar_today,
        Colors.blue
      ),
      (
        'Assign fee items before billing',
        'A bill cannot be generated for a student unless fee items have been assigned to their '
        'class for the active term. Do this under Bills & Payment → Fee Items → Assign to Class.',
        Icons.payments,
        Colors.teal
      ),
      (
        'Bills automatically carry forward unpaid balances',
        'When you generate a bill in a new term, any unpaid balance from previous terms is '
        'automatically included as "Previous Balance" in the student\'s grand total.',
        Icons.account_balance_wallet,
        Colors.orange
      ),
      (
        'Use zero (0) as default fee amount',
        'When defining a fee item, use 0 as the default amount if different classes pay different '
        'amounts. You set the actual amount per class during the "Assign to Class" step.',
        Icons.money_off_outlined,
        Colors.indigo
      ),
      (
        'Back up daily — especially before changing terms',
        'Use Preferences → Backup every day. Always back up before activating a new term. '
        'A Google Drive backup ensures your data is safe even if the device is lost or damaged.',
        Icons.backup,
        Colors.green
      ),
      (
        'Use Daily Report for cash reconciliation',
        'The Daily Report shows all payments collected on a specific date grouped by method. '
        'Use it at the end of each day to balance cash in hand against recorded transactions.',
        Icons.today,
        Colors.deepOrange
      ),
      (
        'Debt Notification letters save time',
        'Instead of writing individual letters, use Bills & Payment → Debt Notification. '
        'Print 2 or 3 letters per page to save paper. Use the PTA and Mid-Term types '
        'for non-debt communications too.',
        Icons.mark_email_unread_outlined,
        Colors.red
      ),
      (
        'Promote students before starting a new session',
        'At the end of each academic year, use Student Management → Promote Students '
        'to move students to their next class in bulk, rather than editing each one individually.',
        Icons.arrow_upward_outlined,
        Colors.purple
      ),
      (
        'Fee Tracker helps monitor partial payments',
        'Use Bills & Payment → Fee Tracker → Set Bill Priority to control which fees are '
        'settled first when a student pays partially. This prevents higher-priority fees '
        'like Tuition from being left unpaid while minor levies are cleared.',
        Icons.track_changes,
        Colors.blueGrey
      ),
    ];

    return Card(
      elevation: 1,
      shadowColor: Colors.black12,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
      child: Padding(
        padding: const EdgeInsets.all(14),
        child: Column(
          children: tips.asMap().entries.map((e) {
            final i = e.key;
            final t = e.value;
            return Column(
              children: [
                if (i > 0) Divider(height: 16, color: Colors.grey.shade100),
                Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Container(
                      padding: const EdgeInsets.all(7),
                      decoration: BoxDecoration(
                        color: t.$4.withValues(alpha: 0.1),
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: Icon(t.$3, size: 18, color: t.$4),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(t.$1,
                              style: const TextStyle(
                                  fontWeight: FontWeight.w600,
                                  fontSize: 13)),
                          const SizedBox(height: 3),
                          Text(t.$2,
                              style: TextStyle(
                                  fontSize: 12,
                                  color: Colors.grey.shade600,
                                  height: 1.4)),
                        ],
                      ),
                    ),
                  ],
                ),
              ],
            );
          }).toList(),
        ),
      ),
    );
  }
}

// ── Data classes ─────────────────────────────────────────────────────────────

class _ModuleData {
  final String title;
  final String subtitle;
  final IconData icon;
  final Color color;
  final List<_Feature> features;

  const _ModuleData({
    required this.title,
    required this.subtitle,
    required this.icon,
    required this.color,
    required this.features,
  });
}

class _Feature {
  final IconData icon;
  final String title;
  final String description;

  const _Feature(this.icon, this.title, this.description);
}

class _Procedure {
  final String title;
  final String description;

  const _Procedure(this.title, this.description);
}

class _SubStep {
  final String label;
  final String body;

  const _SubStep({required this.label, required this.body});
}
